{% set name = "cpputest" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cpputest/cpputest/releases/download/v{{ version }}/cpputest-{{ version }}.tar.gz
  sha256: 81c4958a3ec20ebe87b2cb658c334d27496c715972ddb71262357f449a7c1df3

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

test:
  files:
    - test/
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make

about:
  home: https://github.com/cpputest/cpputest
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  summary: Unit testing and mocking framework for C/C++

  description: |
    CppUTest is a C /C++ based unit xUnit test framework for unit testing
    and for test-driving your code. It is written in C++ but is used in C
    and C++ projects and frequently used in embedded systems but it works
    for any C/C++ project.
  doc_url: http://cpputest.github.io/
  dev_url: https://github.com/cpputest/cpputest/

extra:
  recipe-maintainers:
    - avrahamshukron
